### ISSUE TITLE
Big Sur ALC298PluginFix not work anymore

### ISSUE THREAD

**Issue by jasjang** [jardenliu/XPS15-9560-Ventura#179] opened 2020-11-16 10:02 UTC
When I use the fix
It always shows 

mount_apfs: volume could not be mounted: Permission denied
mount: / failed with 66

I've try to mount it. But still the permission deny.

Please help me to fix it.

**Comment by arachnophilia1997** [comment] 2020-11-18 01:23
check out verb stub kext by kns speed https://www.tonymacx86.com/threads/guide-dell-xps-15-9560-4k-touch-1tb-ssd-32gb-ram-100-adobergb.224486/page-9#post-1539760.

there's some steps. i don't know if they're working in new Big Sur but this alternative audio solution has been working since it was released without any updates as far as i know.

**Comment by nmnobre** [comment] 2020-11-20 18:03
> When I use the fix
> It always shows
> 
> mount_apfs: volume could not be mounted: Permission denied
> mount: / failed with 66
> 
> I've try to mount it. But still the permission deny.
> 
> Please help me to fix it.

You need to follow this [guide](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#writing-to-the-macos-system-partition). In Big Sur you run on a snapshot of the system volume. So you need to live mount the system volume, do your edits (copy `ALCPlugFix` and `hda-verb` to `~/livemount/usr/bin/` and set the right permissions), and then create and bless a new snapshot. The daemon lives in the data partition so you can copy it to its rightful place at any moment.

Note that you will need to edit your `config.plist` to disable the new authenticated root SIP flag before doing any edits. This will enable you to boot from your new, broken-seal snapshot.

I can confirm this worked on my XPS15 9560. My headphones work at full volume. Caveat: doing this deleted my original, sealed snapshot, [I don't know why](https://www.reddit.com/r/hackintosh/comments/jtrop9/big_sur_edited_system_volume_sealed_snapshot_got/)... This might complicate operating system updates, I don't know, I'm waiting for the first one to find out what happens 🙃

**Comment by jardenliu** [comment] 2020-11-26 15:17
latest commit fixed it

**Closed as completed by jardenliu** 2020-11-26 15:17 UTC
